spring:
  datasource:
    url: postgresql://postgres:BNbmBPdwUzcRNUKPNTocyuAwNontdFii@postgres.railway.internal:5432/railway
    username: postgres
    password: BNbmBPdwUzcRNUKPNTocyuAwNontdFii
  jpa:
    hibernate:
      ddl-auto: none #'update' 로 처음 실행 후 'none' 으로 변경
    show-sql: false
    open-in-view: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

hrbank:
  storage:
    local.root-path: "${user.dir}/hrbank-storage" # users.dir 고려
    backup: "${user.dir}/backups"
    file-name: "/tmpBackup.csv"

logging:
  level:
    root: warn
