spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none #'update' 로 처음 실행 후 'none' 으로 변경
    show-sql: true
    open-in-view: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


hrbank:
  storage:
    local.root-path: "${user.dir}.hrbank-storage" # users.dir 고려
    backup: "${user.dir}.backups"
    file-name: "/tmpBackup.csv"
