spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false


hrbank:
  storage:
    local.root-path: "C:\\hrbank-storage"