spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none #'update' 로 처음 실행 후 'none' 으로 변경
    show-sql: true
    open-in-view: false
  batch:
    jdbc:
      initialize-schema: always


hrbank:
  storage:
    local.root-path: "C:\\hrbank-storage"
    backup: "${user.dir}/backups"
