spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hrbank}
    url: jdbc:postgresql://part1-hrbank-team7.railway.internal:26333/railway
    username: postgres
    password: BNbmBPdwUzcRNUKPNTocyuAwNontdFii
  jpa:
    hibernate:
      ddl-auto: none #'update' 로 처음 실행 후 'none' 으로 변경
    show-sql: false
    open-in-view: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

hrbank:
  storage:
    local.root-path: "${user.dir}/hrbank-storage" # users.dir 고려
    backup: "${user.dir}/backups"
    file-name: "/tmpBackup.csv"

logging:
  level:
    root: warn
