spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


hrbank:
  storage:
    local.root-path: "C:\\hrbank-storage"