spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hrbank}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hrbank}
    username: ${DB_USERNAME:hrbank}
    password: ${DB_PASSWORD:1234}
#    hikari:
#      maximum-pool-size: 2
#      minimum-idle: 1
#      idle-timeout: 15000
#      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: none #'update' 로 처음 실행 후 'none' 으로 변경
    show-sql: true
    open-in-view: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

hrbank:
  storage:
    local.root-path: "${user.dir}/hrbank-storage" # users.dir 고려
    backup: "${user.dir}/backups"
    file-name: "/tmpBackup.csv"

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    url: /hrbank.json
    path: /swagger-ui.html
